import test from 'node:test';
import assert from 'node:assert/strict';
import { createProject,addInterview,sampleProject,validEvidence } from '../lib/research.ts';
import { analyzeInterviews,runModel,chunks } from '../lib/model-client.ts';
const make=()=>{let p={...createProject(),confirmed:true,objective:'发现提交问题',target:'用户',questions:['提交时有什么困难？']};return addInterview(p,'a','受访者：没有反馈，我又点了一次。','P01');};
const observation=(quote='没有反馈，我又点了一次。')=>({summary:'用户重复点击',theme:'提交反馈',origin:'emergent',stage:'提交',behavior:'重复点击',pain:'反馈不明',question:'提交时有什么困难？',quote,speaker:'participant'});
function mock(t,handler){const previous=globalThis.fetch;globalThis.fetch=async(_url,options)=>handler(JSON.parse(options.body));t.after(()=>{globalThis.fetch=previous;});}
const ok=result=>new Response(JSON.stringify({result}),{status:200,headers:{'content-type':'application/json'}});
test('长文本分块完整保留中文与emoji，无静默截断',()=>{const text=('甲😀乙\n').repeat(3000);const parts=chunks(text);assert.equal(parts.map(p=>p.text).join(''),text);for(const p of parts)assert.equal(text.slice(p.start,p.start+p.text.length),p.text);});
test('AI候选逐字校验，拒绝不存在的引文',async t=>{mock(t,({step,input})=>{if(step==='observations')return ok({observations:[observation(),observation('编造的原话')]});return ok({findings:[{summary:'用户重复点击',theme:'提交反馈',origin:'emergent',stage:'提交',behavior:'重复点击',pain:'反馈不明',question:'提交时有什么困难？',observations:[{id:input.observations[0].id,role:'support'}]}]});});const p=await analyzeInterviews(make(),new AbortController().signal,()=>{});assert.equal(p.evidence.length,1);assert.ok(validEvidence(p,p.evidence[0]));assert.equal(p.findings.length,1);assert.match(p.runs.at(-1).detail,/拒绝 1 条/);});
test('服务失败不制造观察，材料标为失败',async t=>{mock(t,()=>new Response(JSON.stringify({error:'服务暂不可用'}),{status:503}));const p=await analyzeInterviews(make(),new AbortController().signal,()=>{});assert.equal(p.interviews[0].status,'failed');assert.equal(p.evidence.length,0);assert.equal(p.findings.length,0);assert.equal(p.runs.at(-1).status,'failed');});
test('无效聚合ID退回真实观察，不丢失有效提取',async t=>{mock(t,({step})=>step==='observations'?ok({observations:[observation()]}):ok({findings:[{...observation(),observations:[{id:'invented',role:'support'}]}]}));const p=await analyzeInterviews(make(),new AbortController().signal,()=>{});assert.equal(p.findings.length,1);assert.equal(p.evidence.length,1);assert.ok(p.runs.some(r=>r.step==='aggregate'&&r.status==='failed'));});
test('取消后保留已完成材料的观察，未完成材料不冒充完成',async t=>{const abort=new AbortController();let p=addInterview(make(),'b','受访者：另一次体验。','P02');mock(t,()=>{abort.abort();return ok({observations:[observation()]});});p=await analyzeInterviews(p,abort.signal,()=>{});assert.equal(p.findings.length,1);assert.equal(p.interviews[0].status,'analyzed');assert.equal(p.interviews[1].status,'failed');});
test('背景来源不存在时明确提示核对',async t=>{mock(t,()=>ok({objective:'目标',target:'对象',questions:['问题'],themes:[],notes:[{field:'目标',source:'brief',quote:'不存在的来源',issue:'来自背景'}]}));const p=await runModel(make(),'context',new AbortController().signal);assert.equal(p.confirmed,false);assert.match(p.notes[0].issue,/未通过匹配/);});
test('洞察不得引用不存在的发现',async t=>{const p=sampleProject();p.findings[0].status='confirmed';mock(t,()=>ok({insights:[{question:p.questions[0],findingIds:['invented'],interpretation:'解释',judgment:'',opportunity:'',hypothesis:'',validation:'',limitations:''}]}));await assert.rejects(runModel(p,'insights',new AbortController().signal),/不存在/);});
